### ISSUE TITLE
[Bug] Locales patterns rules are inconsistent

### ISSUE THREAD

**Issue by overtrue** [pagekit/vue-intl#1]
I found that patterns rules(`$locale.TIMESPAN_FORMATS`) are inconsistent，Not all language packs have the rule `one` (ex:`zh-CN`):

![qq20160428-0 2x](https://cloud.githubusercontent.com/assets/1472352/14876461/b4130e66-0d47-11e6-9017-f1b5af5f2125.png)

So, when the variable `number`([Line 72](https://github.com/pagekit/vue-intl/blob/master/src/relative.js#L73)) is `1`, the error will be thrown:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
```

So this line needs to check for the presence of the property: https://github.com/pagekit/vue-intl/blob/master/src/relative.js#L73

**Comment by MalteScharenberg** [comment]
Thanks for reporting! This should fix the issue: https://github.com/pagekit/vue-intl/commit/e0e9469c97cf1f5edd3e22d38ecbe64846a85277.

**Comment by overtrue** [comment]
👍
